# Generated by Django 2.1.5 on 2019-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nom')),
                ('address', models.CharField(max_length=180, verbose_name='adresse')),
                ('contact', models.CharField(max_length=100, verbose_name='personne de contact')),
            ],
            options={
                'verbose_name': 'Company',
                'ordering': ['name'],
            },
        ),
    ]
