# Generated by Django 2.1.5 on 2019-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Suisse', max_length=80, verbose_name='pays'),
        ),
    ]
