# Generated by Django 2.1.5 on 2019-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_company_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='nom')),
                ('month', models.CharField(max_length=20, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Month',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='année')),
            ],
            options={
                'verbose_name': 'Year',
            },
        ),
    ]
