# Generated by Django 2.1.5 on 2019-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(max_length=20, unique=True, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='month',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='num'),
        ),
    ]
