# Generated by Django 2.1.5 on 2019-01-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20190130_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuCompta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.FloatField(default=0.0, verbose_name='CA')),
                ('frais_achat', models.FloatField(default=0.0, verbose_name="Frais d'achat")),
                ('charges_sociales', models.FloatField(default=0.0, verbose_name='Charges sociales')),
                ('fg', models.FloatField(default=0.0, verbose_name='Frais généraux')),
                ('autres_frais', models.FloatField(default=0.0, verbose_name='Autres frais')),
                ('ebitda', models.FloatField(default=0.0, verbose_name='EBITDA')),
                ('credits_ct', models.FloatField(default=0.0, verbose_name='Crédits courts termes')),
                ('credits_lt', models.FloatField(default=0.0, verbose_name='Crédits long termes')),
                ('cashflow', models.FloatField(default=0.0, verbose_name='Cashflow')),
                ('investissements', models.FloatField(default=0.0, verbose_name='Investissements')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Company')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Year')),
            ],
            options={
                'verbose_name': 'FormuCompta',
                'ordering': ['year', 'month'],
            },
        ),
    ]
