# Generated by Django 2.1.5 on 2019-01-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_formucompta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formucompta',
            options={'ordering': ['-year', 'month'], 'verbose_name': 'FormuCompta'},
        ),
    ]
